"""create_firewall_backup_table

Revision ID: 12fdec483877
Revises: fee76fcc934c
Create Date: 2026-01-09 12:07:00.500423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '12fdec483877'
down_revision = 'fee76fcc934c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SUMMARY_TABLE_FIREWALL_LOGS_BACKUP_NEW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('host_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('failed_hosts', sa.Text(), nullable=True),
    sa.Column('successful_hosts', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SUMMARY_TABLE_FIREWALL_LOGS_BACKUP_NEW_id'), 'SUMMARY_TABLE_FIREWALL_LOGS_BACKUP_NEW', ['id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_table('menu_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_permissions_id'), 'menu_permissions', ['id'], unique=False)
    op.drop_table('summary_table_firewall_logs_backup_new')
    op.create_index(op.f('ix_catalogue_categories_id'), 'catalogue_categories', ['id'], unique=False)
    op.create_index(op.f('ix_catalogue_permissions_id'), 'catalogue_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_catalogue_role_permissions_id'), 'catalogue_role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_catalogues_id'), 'catalogues', ['id'], unique=False)
    op.add_column('morning-checklist', sa.Column('IP', sa.String(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('APPLICATION_NAME', sa.String(length=255), nullable=False))
    op.add_column('morning-checklist', sa.Column('MC_OUTPUT', sa.Text(), nullable=True))
    op.add_column('morning-checklist', sa.Column('MC_GROUP', sa.String(length=255), nullable=True))
    op.add_column('morning-checklist', sa.Column('MC_CHECK_DATE', sa.Date(), nullable=False))
    op.add_column('morning-checklist', sa.Column('MC_STATUS', sa.String(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('ASSET_OWNER', sa.String(length=255), nullable=True))
    op.add_column('morning-checklist', sa.Column('MC_DIFF_STATUS', sa.String(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('MC_CRITICALITY', sa.String(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('UPDATED_BY', sa.String(length=255), nullable=True))
    op.add_column('morning-checklist', sa.Column('IS_VALIDATED', sa.Boolean(), nullable=True))
    op.add_column('morning-checklist', sa.Column('UPDATED_AT', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_mc_application', table_name='morning-checklist')
    op.create_index('idx_mc_application', 'morning-checklist', ['APPLICATION_NAME'], unique=False)
    op.drop_index('idx_mc_check_date', table_name='morning-checklist')
    op.create_index('idx_mc_check_date', 'morning-checklist', ['MC_CHECK_DATE'], unique=False)
    op.drop_index('idx_mc_owner', table_name='morning-checklist')
    op.create_index('idx_mc_owner', 'morning-checklist', ['ASSET_OWNER'], unique=False)
    op.create_index(op.f('ix_morning-checklist_id'), 'morning-checklist', ['id'], unique=False)
    op.drop_column('morning-checklist', 'mc_criticality')
    op.drop_column('morning-checklist', 'application_name')
    op.drop_column('morning-checklist', 'mc_status')
    op.drop_column('morning-checklist', 'is_validated')
    op.drop_column('morning-checklist', 'updated_by')
    op.drop_column('morning-checklist', 'mc_output')
    op.drop_column('morning-checklist', 'asset_owner')
    op.drop_column('morning-checklist', 'updated_at')
    op.drop_column('morning-checklist', 'mc_group')
    op.drop_column('morning-checklist', 'ip')
    op.drop_column('morning-checklist', 'mc_check_date')
    op.drop_column('morning-checklist', 'mc_diff_status')
    op.create_index(op.f('ix_morning_checklist_validations_id'), 'morning_checklist_validations', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_mapping_id'), 'user_role_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_user_role_mapping_id'), table_name='user_role_mapping')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_morning_checklist_validations_id'), table_name='morning_checklist_validations')
    op.add_column('morning-checklist', sa.Column('mc_diff_status', sa.VARCHAR(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('mc_check_date', oracle.DATE(), nullable=False))
    op.add_column('morning-checklist', sa.Column('ip', sa.VARCHAR(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('mc_group', sa.VARCHAR(length=255), nullable=True))
    op.add_column('morning-checklist', sa.Column('updated_at', oracle.DATE(), nullable=True))
    op.add_column('morning-checklist', sa.Column('asset_owner', sa.VARCHAR(length=255), nullable=True))
    op.add_column('morning-checklist', sa.Column('mc_output', sa.CLOB(), nullable=True))
    op.add_column('morning-checklist', sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True))
    op.add_column('morning-checklist', sa.Column('is_validated', sa.INTEGER(), nullable=True))
    op.add_column('morning-checklist', sa.Column('mc_status', sa.VARCHAR(length=64), nullable=True))
    op.add_column('morning-checklist', sa.Column('application_name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('morning-checklist', sa.Column('mc_criticality', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_morning-checklist_id'), table_name='morning-checklist')
    op.drop_index('idx_mc_owner', table_name='morning-checklist')
    op.create_index('idx_mc_owner', 'morning-checklist', ['asset_owner'], unique=False)
    op.drop_index('idx_mc_check_date', table_name='morning-checklist')
    op.create_index('idx_mc_check_date', 'morning-checklist', ['mc_check_date'], unique=False)
    op.drop_index('idx_mc_application', table_name='morning-checklist')
    op.create_index('idx_mc_application', 'morning-checklist', ['application_name'], unique=False)
    op.drop_column('morning-checklist', 'UPDATED_AT')
    op.drop_column('morning-checklist', 'IS_VALIDATED')
    op.drop_column('morning-checklist', 'UPDATED_BY')
    op.drop_column('morning-checklist', 'MC_CRITICALITY')
    op.drop_column('morning-checklist', 'MC_DIFF_STATUS')
    op.drop_column('morning-checklist', 'ASSET_OWNER')
    op.drop_column('morning-checklist', 'MC_STATUS')
    op.drop_column('morning-checklist', 'MC_CHECK_DATE')
    op.drop_column('morning-checklist', 'MC_GROUP')
    op.drop_column('morning-checklist', 'MC_OUTPUT')
    op.drop_column('morning-checklist', 'APPLICATION_NAME')
    op.drop_column('morning-checklist', 'IP')
    op.drop_index(op.f('ix_catalogues_id'), table_name='catalogues')
    op.drop_index(op.f('ix_catalogue_role_permissions_id'), table_name='catalogue_role_permissions')
    op.drop_index(op.f('ix_catalogue_permissions_id'), table_name='catalogue_permissions')
    op.drop_index(op.f('ix_catalogue_categories_id'), table_name='catalogue_categories')
    op.create_table('summary_table_firewall_logs_backup_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_date', oracle.DATE(), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('host_count', sa.INTEGER(), nullable=True),
    sa.Column('failed_count', sa.INTEGER(), nullable=True),
    sa.Column('failed_hosts', sa.CLOB(), nullable=True),
    sa.Column('successful_hosts', sa.CLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sys_c008328'),
    oracle_tablespace='USERS'
    )
    op.drop_index(op.f('ix_menu_permissions_id'), table_name='menu_permissions')
    op.drop_table('menu_permissions')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_SUMMARY_TABLE_FIREWALL_LOGS_BACKUP_NEW_id'), table_name='SUMMARY_TABLE_FIREWALL_LOGS_BACKUP_NEW')
    op.drop_table('SUMMARY_TABLE_FIREWALL_LOGS_BACKUP_NEW')
    # ### end Alembic commands ###

