"""Initial_migration_squashed

Revision ID: 864dc67102c0
Revises: 
Create Date: 2025-12-13 16:43:55.018782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864dc67102c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_catalogue_categories_id'), 'catalogue_categories', ['id'], unique=False)
    op.create_table('ipam_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=100), nullable=True),
    sa.Column('network_zone', sa.String(length=100), nullable=True),
    sa.Column('segment_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment')
    )
    op.create_table('morning-checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=255), nullable=False),
    sa.Column('IP', sa.String(length=64), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('APPLICATION_NAME', sa.String(length=255), nullable=False),
    sa.Column('Asset_Status', sa.String(length=64), nullable=True),
    sa.Column('Commands', sa.String(length=500), nullable=True),
    sa.Column('MC_OUTPUT', sa.Text(), nullable=True),
    sa.Column('MC_GROUP', sa.String(length=255), nullable=True),
    sa.Column('MC_CHECK_DATE', sa.Date(), nullable=False),
    sa.Column('MC_STATUS', sa.String(length=64), nullable=True),
    sa.Column('ASSET_OWNER', sa.String(length=255), nullable=True),
    sa.Column('MC_DIFF_STATUS', sa.String(length=64), nullable=True),
    sa.Column('MC_CRITICALITY', sa.String(length=64), nullable=True),
    sa.Column('UPDATED_BY', sa.String(length=255), nullable=True),
    sa.Column('IS_VALIDATED', sa.Boolean(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mc_application', 'morning-checklist', ['APPLICATION_NAME'], unique=False)
    op.create_index('idx_mc_check_date', 'morning-checklist', ['MC_CHECK_DATE'], unique=False)
    op.create_index('idx_mc_hostname', 'morning-checklist', ['Hostname'], unique=False)
    op.create_index('idx_mc_owner', 'morning-checklist', ['ASSET_OWNER'], unique=False)
    op.create_index(op.f('ix_morning-checklist_id'), 'morning-checklist', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('catalogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('frontend_route', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalogue_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_catalogues_id'), 'catalogues', ['id'], unique=False)
    op.create_table('ipam_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'UNASSIGNED', 'RESERVED', name='ipamstatus'), nullable=True),
    sa.Column('ritm', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['ipam_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['ipam_segments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_checklist_signoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mc_check_date', sa.Date(), nullable=False),
    sa.Column('validate_by', sa.Integer(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validate_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['validate_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_morning_checklist_signoff_mc_check_date'), 'morning_checklist_signoff', ['mc_check_date'], unique=False)
    op.create_table('morning_checklist_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('asset_owner', sa.String(length=255), nullable=True),
    sa.Column('mc_check_date', sa.Date(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validate_by', sa.Integer(), nullable=False),
    sa.Column('validate_comment', sa.Text(), nullable=True),
    sa.Column('mc_criticality', sa.String(length=64), nullable=True),
    sa.Column('is_bulk', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['validate_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mc_validation_date', 'morning_checklist_validations', ['mc_check_date'], unique=False)
    op.create_index('idx_mc_validation_hostname', 'morning_checklist_validations', ['hostname'], unique=False)
    op.create_index(op.f('ix_morning_checklist_validations_id'), 'morning_checklist_validations', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('user_role_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_dl', sa.Boolean(), nullable=True),
    sa.Column('dl_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_mapping_id'), 'user_role_mapping', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('catalogue_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dl_name', sa.String(length=255), nullable=True),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_permissions_id'), 'catalogue_permissions', ['id'], unique=False)
    op.create_table('catalogue_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_role_permissions_id'), 'catalogue_role_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_role_permissions_id'), table_name='catalogue_role_permissions')
    op.drop_table('catalogue_role_permissions')
    op.drop_index(op.f('ix_catalogue_permissions_id'), table_name='catalogue_permissions')
    op.drop_table('catalogue_permissions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_role_mapping_id'), table_name='user_role_mapping')
    op.drop_table('user_role_mapping')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_morning_checklist_validations_id'), table_name='morning_checklist_validations')
    op.drop_index('idx_mc_validation_hostname', table_name='morning_checklist_validations')
    op.drop_index('idx_mc_validation_date', table_name='morning_checklist_validations')
    op.drop_table('morning_checklist_validations')
    op.drop_index(op.f('ix_morning_checklist_signoff_mc_check_date'), table_name='morning_checklist_signoff')
    op.drop_table('morning_checklist_signoff')
    op.drop_table('ipam_audit_logs')
    op.drop_table('ipam_allocations')
    op.drop_index(op.f('ix_catalogues_id'), table_name='catalogues')
    op.drop_table('catalogues')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_morning-checklist_id'), table_name='morning-checklist')
    op.drop_index('idx_mc_owner', table_name='morning-checklist')
    op.drop_index('idx_mc_hostname', table_name='morning-checklist')
    op.drop_index('idx_mc_check_date', table_name='morning-checklist')
    op.drop_index('idx_mc_application', table_name='morning-checklist')
    op.drop_table('morning-checklist')
    op.drop_table('ipam_segments')
    op.drop_index(op.f('ix_catalogue_categories_id'), table_name='catalogue_categories')
    op.drop_table('catalogue_categories')
    # ### end Alembic commands ###

